#!/usr/bin/env python3

# Copyright 2024 Universidad Politécnica de Madrid
# SPDX-License-Identifier: BSD-3-Clause

"""Snapshot mission — generated by snapshot_mission.py.

Covers only the waypoints that were unvisited when the previous experiment
was stopped.  Drone starting positions are set in config/world_snapshot.yaml.

Usage:
    python3 snapshot_mission_gen.py [-s]
"""

import argparse
import json
from time import sleep

from as2_msgs.msg import MissionUpdate
import rclpy
from rclpy.node import Node

# ── Parameters ────────────────────────────────────────────────────────────────
ALL_DRONES = ['drone0', 'drone1', 'drone3', 'drone4']

TAKEOFF_HEIGHT = 1.0   # metres
TAKEOFF_SPEED  = 0.7    # m/s

# Remaining inspection waypoints (unvisited at snapshot time).
AUCTION_POINTS = [
    {'name': 'panel_A1', 'feature_names': ['x', 'y'], 'features': [-9.0, 6.0]},
    {'name': 'panel_A2', 'feature_names': ['x', 'y'], 'features': [-6.0, 6.0]},
    {'name': 'panel_A3', 'feature_names': ['x', 'y'], 'features': [-3.0, 6.0]},
    {'name': 'panel_A4', 'feature_names': ['x', 'y'], 'features': [0.0, 6.0]},
    {'name': 'panel_A5', 'feature_names': ['x', 'y'], 'features': [3.0, 6.0]},
    {'name': 'panel_A6', 'feature_names': ['x', 'y'], 'features': [6.0, 6.0]},
    {'name': 'panel_A7', 'feature_names': ['x', 'y'], 'features': [9.0, 6.0]},
    {'name': 'panel_B1', 'feature_names': ['x', 'y'], 'features': [-9.0, 3.0]},
    {'name': 'panel_B2', 'feature_names': ['x', 'y'], 'features': [-6.0, 3.0]},
    {'name': 'panel_B3', 'feature_names': ['x', 'y'], 'features': [-3.0, 3.0]},
    {'name': 'panel_B4', 'feature_names': ['x', 'y'], 'features': [0.0, 3.0]},
    {'name': 'panel_B5', 'feature_names': ['x', 'y'], 'features': [3.0, 3.0]},
    {'name': 'panel_B6', 'feature_names': ['x', 'y'], 'features': [6.0, 3.0]},
    {'name': 'panel_B7', 'feature_names': ['x', 'y'], 'features': [9.0, 3.0]},
    {'name': 'panel_C1', 'feature_names': ['x', 'y'], 'features': [-9.0, 0.0]},
    {'name': 'panel_C2', 'feature_names': ['x', 'y'], 'features': [-6.0, 0.0]},
    {'name': 'panel_C3', 'feature_names': ['x', 'y'], 'features': [-3.0, 0.0]},
    {'name': 'panel_C4', 'feature_names': ['x', 'y'], 'features': [0.0, 0.0]},
    {'name': 'panel_C5', 'feature_names': ['x', 'y'], 'features': [3.0, 0.0]},
    {'name': 'panel_C6', 'feature_names': ['x', 'y'], 'features': [6.0, 0.0]},
    {'name': 'panel_C7', 'feature_names': ['x', 'y'], 'features': [9.0, 0.0]},
    {'name': 'panel_D1', 'feature_names': ['x', 'y'], 'features': [-9.0, -3.0]},
    {'name': 'panel_D2', 'feature_names': ['x', 'y'], 'features': [-6.0, -3.0]},
    {'name': 'panel_D3', 'feature_names': ['x', 'y'], 'features': [-3.0, -3.0]},
    {'name': 'panel_D4', 'feature_names': ['x', 'y'], 'features': [0.0, -3.0]},
    {'name': 'panel_D5', 'feature_names': ['x', 'y'], 'features': [3.0, -3.0]},
    {'name': 'panel_D6', 'feature_names': ['x', 'y'], 'features': [6.0, -3.0]},
    {'name': 'panel_D7', 'feature_names': ['x', 'y'], 'features': [9.0, -3.0]},
    {'name': 'panel_E1', 'feature_names': ['x', 'y'], 'features': [-9.0, -6.0]},
    {'name': 'panel_E2', 'feature_names': ['x', 'y'], 'features': [-6.0, -6.0]},
    {'name': 'panel_E3', 'feature_names': ['x', 'y'], 'features': [-3.0, -6.0]},
    {'name': 'panel_E4', 'feature_names': ['x', 'y'], 'features': [0.0, -6.0]},
    {'name': 'panel_E5', 'feature_names': ['x', 'y'], 'features': [3.0, -6.0]},
    {'name': 'panel_E6', 'feature_names': ['x', 'y'], 'features': [6.0, -6.0]},
    {'name': 'panel_E7', 'feature_names': ['x', 'y'], 'features': [9.0, -6.0]},
]

MISSION_ID = 0
# ──────────────────────────────────────────────────────────────────────────────


class BeginMission(Node):
    """Publishes EXECUTE missions to the ROS 2 mission interpreter adapter."""

    def __init__(self, use_sim_time: bool = False):
        super().__init__('begin_mission')
        self.set_parameters([
            rclpy.parameter.Parameter(
                'use_sim_time', rclpy.parameter.Parameter.Type.BOOL, use_sim_time
            )
        ])
        self._mission_pub = {
            drone: self.create_publisher(MissionUpdate, f'/{drone}/mission_update', 10)
            for drone in ALL_DRONES
        }

    def _send_mission(self, drone_id: str, plan: list) -> None:
        mission = {'target': drone_id, 'plan': plan}
        msg = MissionUpdate()
        msg.drone_id = drone_id
        msg.mission_id = MISSION_ID
        msg.action = MissionUpdate.EXECUTE
        msg.mission = json.dumps(mission)
        self._mission_pub[drone_id].publish(msg)
        self.get_logger().info(f'[{drone_id}] mission sent: {[item["behavior"] for item in plan]}')

    def run(self) -> None:
        sleep(1.0)

        # Auctioneer: takeoff → auction
        self._send_mission(
            'drone0',
            [
                {'behavior': 'takeoff',
                  'args': {'height': TAKEOFF_HEIGHT, 'speed': TAKEOFF_SPEED}},
                {'behavior': 'auction',
                  'args': {
                      'name': 'snapshot_point_assignment',
                      'elements': AUCTION_POINTS,
                      'auction_type': 'coordinate_item',
                      'bidders': ALL_DRONES,
                  }},
            ],
        )
        # Participants: takeoff only (they join the auction via CA gateway)
        for drone in ['drone1', 'drone3', 'drone4']:
            self._send_mission(
                drone,
                [{'behavior': 'takeoff',
                  'args': {'height': TAKEOFF_HEIGHT, 'speed': TAKEOFF_SPEED}}],
            )


def main():
    parser = argparse.ArgumentParser(description='Run snapshot mission')
    parser.add_argument('-s', '--use_sim_time', action='store_true', default=False)
    args = parser.parse_args()

    rclpy.init()
    node = BeginMission(use_sim_time=args.use_sim_time)
    node.run()
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
