/**:
  platform:
    ros__parameters:
      gps_origin:
        latitude: 40.4405287
        longitude: -3.6898277
        altitude: 100.0

drone0:
  platform:
    ros__parameters:
      vehicle_initial_pose:
        x: -4.0  # drone0 starts south-west → flies to north-east
        y: -4.0
        z: 0.0

drone1:
  platform:
    ros__parameters:
      vehicle_initial_pose:
        x: 4.0   # drone1 starts south-east → flies to north-west
        y: -4.0
        z: 0.0
