/**:
  platform:
    ros__parameters:
      gps_origin:
        latitude: 40.4405287
        longitude: -3.6898277
        altitude: 100.0

drone0:
  platform:
    ros__parameters:
      vehicle_initial_pose:
        x: -10.0
        y: 9.0
        z: 0.0

drone1:
  platform:
    ros__parameters:
      vehicle_initial_pose:
        x: -10.0
        y: 3.0
        z: 0.0

drone2:
  platform:
    ros__parameters:
      vehicle_initial_pose:
        x: -10.0
        y: -3.0
        z: 0.0

drone3:
  platform:
    ros__parameters:
      vehicle_initial_pose:
        x: -10.0
        y: -9.0
        z: 0.0
